### ISSUE TITLE
[themes] Export styles

### ISSUE THREAD

**Issue by agritheory** [agritheory/stonecrop#99]
Document how styles should be added to the project and how to include them in Vue projects

**Comment by agritheory** [comment]
@Alchez This should be quick, but let's use this ticket to update the documentation to NPM install and include instructions on importing the styles (like you're working on in the AR context)

**Comment by agritheory** [comment]
Using this inside a component's `style` tag: like `import '@stonecrop/themes/default';`  surfaces a warning on build 

```
vite v5.4.10 building for production...
✓ 2 modules transformed.
x Build failed in 56ms
error during build:
[vite]: Rollup failed to resolve import "@stonecrop/themes/default" from "/home/tyler/larch/apps/fab/fab/ui/forecast/forecast.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///home/tyler/larch/apps/fab/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:65589:17)
    at onRollupWarning (file:///home/tyler/larch/apps/fab/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:65621:5)
    at onwarn (file:///home/tyler/larch/apps/fab/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:65284:7)
    at file:///home/tyler/larch/apps/fab/node_modules/rollup/dist/es/shared/node-entry.js:19409:13
    at Object.logger [as onLog] (file:///home/tyler/larch/apps/fab/node_modules/rollup/dist/es/shared/node-entry.js:21135:9)
    at ModuleLoader.handleInvalidResolvedId (file:///home/tyler/larch/apps/fab/node_modules/rollup/dist/es/shared/node-entry.js:20024:26)
    at file:///home/tyler/larch/apps/fab/node_modules/rollup/dist/es/shared/node-entry.js:19982:26
    ```
